name: Create ISO Image from Repository Files

on:
  push:
    branches:
      - main  # またはデフォルトブランチ名
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mkisofs
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      - name: Create ISO image
        run: |
          mkdir -p output
          # デフォルトのチェックアウトディレクトリをISOに変換
          mkisofs -o output/repository.iso .
          
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: repository-iso
          path: output/repository.iso
